Vagrant.configure("2") do |config|
  config.hostmanager.enabled      = true
  config.hostmanager.manage_host  = true
  config.hostmanager.aliases = %w(mynode.dev)

  config.vm.box = "centos6.4-new"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"
  config.vm.hostname = 'node-box'
  config.vm.network :private_network, ip: "12.12.12.12"
    config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.customize ["modifyvm", :id, "--name", "my-box"]
  end

  nfs_setting = RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/

  config.vm.synced_folder "./", "/vagrant", id: "vagrant-root" , :nfs => nfs_setting

  config.vm.provision :shell, :inline => 'echo -e "mysql_root_password=simplepass
controluser_password=awesome" > /etc/phpmyadmin.facts;'

  config.vm.provision :shell, :path => "./bin/bootstrap.sh"

end
